export function auditActionText(action: string) {
  const labels: Record<string, string> = {
    family_created: "Семья создана",
    family_request_created: "Заявка отправлена",
    family_request_cancelled: "Заявка отменена",
    family_request_approved: "Заявка принята",
    family_request_rejected: "Заявка отклонена",
    family_request_expired: "Заявка истекла",
    family_request_cancelled_family_full: "Заявка закрыта: семья заполнена",
    family_became_full: "Семья заполнена",
    family_access_provided: "Владелец выдал доступ",
    family_access_confirmation_reminded: "Владелец напомнил подтвердить доступ",
    family_access_confirmation_overdue_reminded: "Доступ ожидает подтверждения больше суток",
    family_access_confirmed: "Участник подтвердил доступ",
    first_payment_overdue: "Первый платеж просрочен",
    family_payment_reported: "Участник отметил оплату",
    family_payment_report_cancelled: "Участник отменил отметку оплаты",
    family_payment_confirmed: "Владелец подтвердил оплату",
    family_payment_not_received: "Владелец отметил, что оплату не получил",
    family_payment_cancelled: "Будущий платеж отменен",
    family_prepayment_created: "Участник создал предоплату",
    family_prepayment_recorded_by_owner: "Владелец отметил предоплату",
    regular_payment_created: "Создан регулярный платеж",
    regular_payment_due: "Регулярный платеж к оплате",
    regular_payment_overdue: "Регулярный платеж просрочен",
    family_member_removal_scheduled: "Удаление участника запланировано",
    family_member_removal_revoked: "Удаление участника отменено",
    family_member_removal_acknowledged: "Участник увидел предупреждение об удалении",
    family_member_removal_cancellation_requested: "Участник попросил отменить удаление",
    family_member_removed_by_timeout: "Участник удален после предупреждения",
    family_member_cancelled_before_access: "Вступление отменено до доступа",
    family_member_left: "Участник вышел из семьи",
    family_description_updated: "Описание семьи обновлено",
    family_price_updated: "Стоимость семьи обновлена",
    family_payment_day_updated: "Дата оплаты обновлена",
    family_closing_started: "Семья закрывается",
    family_closing_acknowledged: "Участник подтвердил предупреждение о закрытии",
    family_closed: "Семья закрыта"
  };
  return labels[action] ?? action;
}