import type { FamilyType } from "../types";

export * from "./audit";
export * from "./owner";
export * from "./payments";
export * from "./status";

export const familyTypeLabels: Record<FamilyType, string> = {
  subscription: "Подписки",
  tariff: "Тарифы"
};

export const familyKindLabels: Record<FamilyType, string> = {
  subscription: "Семья подписки",
  tariff: "Семья тарифа"
};

export const requestCancelReasonLabels: Record<string, string> = {
  user_cancelled: "Заявка отменена вами.",
  family_full: "Семья заполнилась до решения владельца."
};

export const errorLabels: Record<string, string> = {
  USERNAME_REQUIRED: "Создайте username в Telegram и снова откройте SubsMarket.",
  TELEGRAM_INIT_DATA_REQUIRED: "Откройте SubsMarket через Telegram Mini App.",
  TELEGRAM_INIT_DATA_EXPIRED: "Сессия Telegram устарела. Закройте и снова откройте Mini App.",
  TELEGRAM_INIT_DATA_HASH_INVALID: "Не удалось проверить Telegram-сессию. Откройте Mini App заново.",
  TELEGRAM_INIT_DATA_HASH_MISSING: "Telegram не передал данные для проверки. Откройте Mini App заново.",
  TELEGRAM_INIT_DATA_AUTH_DATE_MISSING: "Telegram не передал время сессии. Откройте Mini App заново.",
  TELEGRAM_INIT_DATA_AUTH_DATE_INVALID: "Telegram передал некорректную сессию. Откройте Mini App заново.",
  TELEGRAM_INIT_DATA_USER_MISSING: "Telegram не передал профиль пользователя. Откройте Mini App заново.",
  TELEGRAM_INIT_DATA_USER_INVALID: "Telegram передал некорректный профиль. Откройте Mini App заново.",
  TELEGRAM_BOT_TOKEN_NOT_CONFIGURED: "Mini App пока не настроен для проверки Telegram-сессии.",
  TELEGRAM_WEBHOOK_SECRET_REQUIRED: "Webhook бота не настроен.",
  TELEGRAM_WEBHOOK_SECRET_INVALID: "Webhook бота отклонён из-за неверной проверки.",
  DATABASE_NOT_READY: "База данных пока недоступна. Попробуйте ещё раз через минуту.",
  NOT_FOUND: "Запись не найдена.",
  FAMILY_SERVICE_NOT_FOUND: "Сервис не найден или пока недоступен.",
  UNSUPPORTED_FAMILY_PERIOD: "Этот период оплаты недоступен для выбранного сервиса.",
  MAX_MEMBERS_EXCEEDS_SERVICE_LIMIT: "Количество мест больше лимита выбранного сервиса.",
  TARIFF_PLAN_NAME_REQUIRED: "Укажите название тарифа оператора.",
  PLAN_NAME_ONLY_FOR_TARIFF: "Название тарифа можно указывать только для семьи тарифа.",
  OWNER_ACTIVE_FAMILY_LIMIT_REACHED: "Бесплатно можно быть владельцем только двух активных семей.",
  FAMILY_NOT_FOUND: "Семья не найдена.",
  FAMILY_MEMBER_NOT_FOUND: "Участник семьи не найден.",
  FAMILY_PAYMENT_NOT_FOUND: "Платёж не найден.",
  FAMILY_NOT_JOINABLE: "В эту семью сейчас нельзя отправить заявку.",
  FAMILY_NOT_EDITABLE: "Эту семью сейчас нельзя редактировать.",
  FAMILY_PRICE_NOT_EDITABLE: "Цену этой семьи сейчас нельзя изменить.",
  FAMILY_PRICE_ALREADY_UPDATED: "Цену можно менять только один раз в месяц.",
  FAMILY_PAYMENT_DAY_LOCKED: "Дату оплаты можно менять только пока семья ещё не собрана.",
  FAMILY_PAYMENT_DAY_NOT_EDITABLE: "Дату оплаты этой семьи сейчас нельзя изменить.",
  FAMILY_AUDIT_FORBIDDEN: "История семьи доступна только её участникам.",
  ONLY_OWNER_CAN_CHANGE_FAMILY: "Изменять семью может только владелец.",
  OWNER_CANNOT_REQUEST_OWN_FAMILY: "Нельзя отправить заявку в свою семью.",
  ALREADY_IN_FAMILY: "Вы уже состоите в этой семье.",
  FAMILY_REQUEST_FORBIDDEN: "В эту семью повторная заявка недоступна. Выберите другую семью.",
  FAMILY_REQUEST_ALREADY_PENDING: "Заявка уже отправлена. Дождитесь ответа или отмените её.",
  SELF_CANCEL_LIMIT_REACHED: "Вы уже дважды отменяли заявку в эту семью. Повторная заявка недоступна.",
  FAMILY_REQUEST_NOT_FOUND: "Заявка не найдена.",
  FAMILY_REQUEST_NOT_PENDING: "Эта заявка уже не ожидает решения.",
  ONLY_OWNER_CAN_VIEW_REQUESTS: "Заявки может смотреть только владелец семьи.",
  ONLY_OWNER_CAN_APPROVE_REQUEST: "Принять заявку может только владелец семьи.",
  ONLY_OWNER_CAN_REJECT_REQUEST: "Отклонить заявку может только владелец семьи.",
  ONLY_OWNER_CAN_VIEW_MEMBERS: "Участников может смотреть только владелец семьи.",
  MEMBER_CANCEL_FORBIDDEN: "Отменить это вступление может только кандидат или владелец семьи.",
  OWNER_CANNOT_CANCEL_MEMBERSHIP: "Владелец не может отменить своё участие в семье.",
  MEMBER_NOT_AWAITING_ACCESS: "Для этого участника сейчас нельзя выдать доступ.",
  MEMBER_NOT_AWAITING_CONFIRMATION: "Доступ уже подтверждён или этот шаг недоступен.",
  MEMBER_NOT_ACTIVE: "Этот участник сейчас не активен.",
  ACCESS_NOT_CONFIRMED: "Реквизиты откроются только после подтверждения доступа.",
  ONLY_OWNER_CAN_PROVIDE_ACCESS: "Выдать доступ может только владелец семьи.",
  ONLY_OWNER_CAN_REMIND_ACCESS_CONFIRMATION: "Напомнить о доступе может только владелец семьи.",
  ACCESS_REMINDER_COOLDOWN: "Напоминание уже отправлено. Повторите через 10 минут.",
  OWNER_ACCESS_ALREADY_ACTIVE: "Доступ владельца уже активен.",
  ONLY_MEMBER_CAN_CONFIRM_ACCESS: "Подтвердить доступ может только сам участник.",
  PAYMENT_NOT_REPORTABLE: "Этот платёж сейчас нельзя отметить оплаченным.",
  PAYMENT_REPORT_NOT_ACTIVE: "Отметка оплаты уже не активна.",
  PAYMENT_NOT_REPORTED: "Владелец может подтвердить только платёж, отмеченный участником.",
  PAYMENT_REQUISITE_NOT_FOUND: "Реквизиты оплаты не найдены.",
  PAYMENT_REQUISITE_FORBIDDEN: "Реквизиты доступны только участнику и владельцу семьи.",
  FAMILY_PAYMENTS_FORBIDDEN: "Платежи доступны только участнику и владельцу семьи.",
  ONLY_MEMBER_CAN_PREPAY: "Создать предоплату может только сам участник.",
  ONLY_OWNER_CAN_RECORD_PREPAYMENT: "Несколько оплаченных периодов может отметить только владелец.",
  MEMBER_NOT_ELIGIBLE_FOR_PREPAYMENT: "Предоплата доступна только активному участнику.",
  FAMILY_NOT_ELIGIBLE_FOR_PREPAYMENT: "В закрывающейся или закрытой семье предоплата недоступна.",
  MEMBER_PREPAYMENT_LIMIT_REACHED: "Ближайший будущий период уже создан. Несколько периодов отмечает владелец после договоренности.",
  YEARLY_PREPAYMENT_LIMIT_REACHED: "За один раз можно отметить не больше трех годовых периодов.",
  ONLY_MEMBER_CAN_REPORT_PAYMENT: "Отметить оплату может только участник.",
  ONLY_MEMBER_CAN_CANCEL_REPORT: "Отменить отметку оплаты может только участник.",
  ONLY_OWNER_CAN_CONFIRM_PAYMENT: "Подтвердить оплату может только владелец семьи.",
  ONLY_OWNER_CAN_MARK_NOT_RECEIVED: "Отметить неоплату может только владелец семьи.",
  ONLY_MEMBER_CAN_LEAVE: "Выйти из семьи может только сам участник.",
  OWNER_MUST_CLOSE_FAMILY: "Владелец не может просто выйти. Сначала нужно закрыть семью.",
  OWNER_CANNOT_REMOVE_SELF: "Владелец не может удалить себя из семьи.",
  ONLY_OWNER_CAN_REMOVE_MEMBER: "Удалить участника может только владелец семьи.",
  ONLY_OWNER_CAN_REVOKE_REMOVAL: "Отменить удаление может только владелец семьи.",
  MEMBER_NOT_REMOVABLE: "Этого участника сейчас нельзя поставить на удаление.",
  MEMBER_REMOVAL_NOT_PENDING: "Удаление участника сейчас не запланировано.",
  ONLY_MEMBER_CAN_ACK_REMOVAL: "Подтвердить предупреждение об удалении может только сам участник.",
  ONLY_MEMBER_CAN_REQUEST_REMOVAL_CANCELLATION:
    "Попросить отменить удаление может только сам участник.",
  FAMILY_ALREADY_CLOSED: "Семья уже закрыта.",
  FAMILY_CLOSE_DATE_IN_PAST: "Дата закрытия не может быть в прошлом.",
  FAMILY_NOT_CLOSING: "Семья сейчас не находится в процессе закрытия.",
  INVALID_PAYMENT_PHONE: "Укажите номер телефона для оплаты. Номера карт и IBAN запрещены.",
  PAYMENT_PHONE_ONLY_NO_CARD_OR_IBAN: "Укажите только номер телефона. Номера карт и IBAN запрещены.",
  INVALID_INTERNAL_JOB_TOKEN: "Внутренний токен задания неверный.",
  INVALID_FAMILY_INVITE_CODE: "Введите код приглашения из 8 цифр.",
  FAMILY_INVITE_NOT_FOUND: "Код приглашения не найден.",
  FAMILY_INVITE_INACTIVE: "Этот код больше не действует.",
  FAMILY_INVITE_NOT_ACCEPTING: "Семья сейчас не принимает новых участников.",
  FAMILY_INVITE_NOT_EDITABLE: "Для закрывающейся семьи код приглашения недоступен.",
  FAMILY_INVITE_NOT_ACTIVE: "У семьи сейчас нет активного кода приглашения.",
  ONLY_OWNER_CAN_VIEW_INVITE: "Код приглашения доступен только владельцу семьи.",
  FAMILY_VISIBILITY_NOT_EDITABLE: "Видимость закрывающейся семьи изменить нельзя.",
  MARKETPLACE_OPERATOR_LISTING_EXISTS:
    "У вас уже есть объявление для этого оператора. Измените его цену или описание.",
  MARKETPLACE_LISTING_OPERATOR_IMMUTABLE:
    "Оператор опубликованного объявления изменить нельзя. Создайте новое объявление.",
  MARKETPLACE_AMOUNT_BELOW_MINIMUM: "Укажите не менее 1 ГБ.",
  MARKETPLACE_AMOUNT_ABOVE_MAXIMUM:
    "Количество превышает лимит одного перевода у оператора.",
  MARKETPLACE_AMOUNT_INVALID_STEP:
    "Количество не соответствует допустимому шагу оператора.",
  MARKETPLACE_ACTIVE_REQUEST_EXISTS:
    "У вас уже есть активная заявка к этому объявлению.",
  MARKETPLACE_REQUEST_STATUS_CONFLICT: "Статус заявки уже изменился.",
  MARKETPLACE_LISTING_UNAVAILABLE: "Это объявление сейчас недоступно.",
  MARKETPLACE_LISTING_RENEW_TOO_EARLY:
    "Продлить объявление можно в последние сутки его действия.",
  MARKETPLACE_OPERATOR_UNAVAILABLE:
    "Этот оператор сейчас недоступен для новых объявлений и продления.",
  MARKETPLACE_GB_DISABLED: "Раздел гигабайтов пока недоступен.",
  MARKETPLACE_ACCOUNTS_DISABLED: "Раздел аккаунтов пока недоступен.",
  MARKETPLACE_LISTING_NOT_FOUND: "Объявление не найдено.",
  MARKETPLACE_LISTING_ARCHIVED: "Объявление уже закрыто.",
  MARKETPLACE_LISTING_NOT_EDITABLE: "Это объявление сейчас нельзя изменить.",
  MARKETPLACE_LISTING_OWNER_REQUIRED: "Изменить объявление может только продавец.",
  MARKETPLACE_LISTING_RENEW_REQUIRED: "Сначала продлите объявление.",
  MARKETPLACE_LISTING_STATUS_CONFLICT: "Статус объявления уже изменился. Обновите страницу.",
  MARKETPLACE_OPERATOR_REQUIRED: "Выберите мобильного оператора.",
  MARKETPLACE_PRICE_REQUIRED: "Укажите цену за 1 ГБ.",
  MARKETPLACE_OUTCOME_REQUIRED: "Укажите результат заявки.",
  MARKETPLACE_REQUEST_NOT_FOUND: "Заявка на гигабайты не найдена.",
  MARKETPLACE_REQUEST_BUYER_REQUIRED: "Это действие доступно только покупателю.",
  MARKETPLACE_REQUEST_SELLER_REQUIRED: "Это действие доступно только продавцу.",
  MARKETPLACE_SELF_REQUEST_FORBIDDEN: "Нельзя отправить заявку на своё объявление.",
  MARKETPLACE_REMINDER_TOO_EARLY: "Напомнить продавцу можно через два часа после заявки.",
  MARKETPLACE_REMINDER_COOLDOWN: "Напоминание уже отправлено. Повторите позже.",
  ACCOUNT_SERVICE_UNAVAILABLE: "Этот сервис сейчас недоступен для объявлений.",
  ACCOUNT_LISTING_NOT_FOUND: "Объявление аккаунта не найдено.",
  ACCOUNT_LISTING_ARCHIVED: "Объявление аккаунта уже закрыто.",
  ACCOUNT_LISTING_UNAVAILABLE: "Это объявление аккаунта сейчас недоступно.",
  ACCOUNT_LISTING_NOT_EDITABLE: "Это объявление аккаунта сейчас нельзя изменить.",
  ACCOUNT_LISTING_OWNER_REQUIRED: "Изменить объявление может только продавец.",
  ACCOUNT_LISTING_RENEW_REQUIRED: "Сначала продлите объявление.",
  ACCOUNT_LISTING_RENEW_TOO_EARLY: "Продлить объявление можно ближе к окончанию срока.",
  ACCOUNT_LISTING_STATUS_CONFLICT: "Статус объявления уже изменился. Обновите страницу.",
  ACCOUNT_TITLE_REQUIRED: "Укажите название аккаунта или доступа.",
  ACCOUNT_PRICE_REQUIRED: "Укажите цену аккаунта или доступа.",
  ACCOUNT_ACTIVE_REQUEST_EXISTS: "У вас уже есть активная заявка на это объявление.",
  ACCOUNT_REQUEST_NOT_FOUND: "Заявка на аккаунт не найдена.",
  ACCOUNT_REQUEST_BUYER_REQUIRED: "Это действие доступно только покупателю.",
  ACCOUNT_REQUEST_SELLER_REQUIRED: "Это действие доступно только продавцу.",
  ACCOUNT_REQUEST_STATUS_CONFLICT: "Статус заявки уже изменился. Обновите страницу.",
  ACCOUNT_SELF_REQUEST_FORBIDDEN: "Нельзя отправить заявку на своё объявление.",
  ACCOUNT_OUTCOME_REQUIRED: "Укажите результат заявки.",
  ACCOUNT_REMINDER_TOO_EARLY: "Напомнить продавцу можно через два часа после заявки.",
  ACCOUNT_REMINDER_COOLDOWN: "Напоминание уже отправлено. Повторите позже.",
  FAMILY_AVAILABILITY_NOT_EDITABLE: "Количество мест этой семьи сейчас нельзя изменить.",
  FAMILY_NOT_MUTABLE: "Эту семью сейчас нельзя изменить.",
  MONTHLY_PREPAYMENT_LIMIT_REACHED: "За один раз можно отметить не больше 12 месяцев.",
  ONLY_OWNER_CAN_VIEW_PAYMENTS: "Платежи участников доступны только владельцу семьи.",
  INVALID_MEMBER_REMOVAL_REASON: "Выберите причину удаления участника.",
  TELEGRAM_USERNAME_REQUIRED: "Создайте username в Telegram и снова откройте SubsMarket.",
  INVALID_CURSOR: "Список изменился. Обновите его и попробуйте снова.",
  INVALID_PAGE_CURSOR: "Список изменился. Обновите его и попробуйте снова.",
  CURSOR_SORT_MISMATCH: "Сортировка изменилась. Откройте список заново.",
  INVALID_IDEMPOTENCY_KEY: "Не удалось безопасно повторить запрос. Попробуйте снова.",
  IDEMPOTENCY_KEY_REUSED: "Этот запрос уже использован для другого действия.",
  IDEMPOTENCY_REQUEST_IN_PROGRESS: "Запрос уже выполняется. Подождите несколько секунд.",
  RATE_LIMIT_EXCEEDED: "Слишком много попыток. Повторите позже.",
  INTERNAL_JOB_TOKEN_REQUIRED: "Внутренний токен задания не настроен."
};
